apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: argo-app
  namespace: app-shopping-commons
spec:
  destination:
    namespace: app-shopping-commons
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application
  - group: triggers.tekton.dev
    jsonPointers:
    - /status
    kind: EventListener
  - group: triggers.tekton.dev
    jsonPointers:
    - /status
    kind: TriggerTemplate
  - group: triggers.tekton.dev
    jsonPointers:
    - /status
    kind: TriggerBinding
  - group: route.openshift.io
    jsonPointers:
    - /spec/host
    kind: Route
  project: default
  source:
    path: app
    repoURL: http://gogs-gogs.apps.ocp4.klaassen.click/mklaasse/shopping-app-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
