apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-stock-application-argocd-controller
  namespace: app-stock-application
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-stock-application-argocd-rolebinding
  namespace: app-stock-application
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-stock-application-argocd-controller
subjects:
- kind: ServiceAccount
  name: app-stock-argocd-argocd-application-controller
  namespace: app-stock-commons
